### ISSUE TITLE
menu entry to add folder does not show up

### ISSUE THREAD

**Issue by vladtepesch** [ceciliasharp/Extension.FolderToSolutionFolder#10]
![image](https://user-images.githubusercontent.com/1601159/81155931-be0a7480-8f85-11ea-93ed-a891662212c8.png)

I installed the extension in Visual Studio 2015, but the depicted menu entry does not appear in my contextmenu.

**Comment by vladtepesch** [comment]
🙄 seems to be a pebcak error.
The extension seems to be exclusively usefull to add folders to solution (not projects) :-(

https://github.com/ceciliasharp/Extension.FolderToSolutionFolder/issues/9 seems to address the same use case

**Comment by ceciliasharp** [comment]
This is outside the scope of this extension since solution folders only can exist on solutions. This request is add regular files/folder to projects. But will investigate this request.
