### ISSUE TITLE
Cannot add new files after folder creation to source control

### ISSUE THREAD

**Issue by heribertolugo** [ceciliasharp/Extension.FolderToSolutionFolder#12]
I am working with visual studio 2019. After the install i received an error stating the extension could not be installed. After i started visual studio, i noticed the extension was in fact installed.

i right clicked the solution and used the extension to add a folder at the solution level to the solution. The 2 files in the folder were added to solution explorer as expected, even having the icon indicating that they are added to source control.

i right clicked the solution folder in solution explorer and selected add existing. I selected 3 files from a different folder thinking they would be copied to the solution folder. They werent copied, but they were added - however no icon indicating they were added to source control. 

So i went and removed those through solution explorer and added them manually to the folder in the file system expecting them to show in solution explorer - they didnt. there is no "show all files" available to this folder created in the solution. 

So then i right clicked and selected add existing and selected the files i manually added to the solution level folder in the file system. They are added but still do not show as being added to source control.

I do not think that i am trying to add them incorrectly, as i have tried all the ways i see possible. right clicking the files does not give me the option to add to source control.  The only fix i can think of is to remove the solution folder and then re-add it whenever i add new files to the folder in the filesystem. 

Is this behavior by design? when i add items to the filesystem are they not supposed to be added to solution folder? if not, and i must right click to add existing - they are not being added correctly. something seems to be wrong in that they are not being recognized in the same manner as any files in the filesystem when the solution folder is created.

Here is a screenshot of what i mean:
![image_2021-03-08_002921](https://user-images.githubusercontent.com/26213368/110278487-535f0680-7fa5-11eb-9fb2-0c736f867191.png)

**Comment by ceciliasharp** [comment]
I'm sorry to say that this is the design of the feature "Solution Folders". Initially, those solution folders were designed just to support; project inside a solution. To organize them into groups when having large solutions. But the structure makes them "perfect" for files not belonging to a particular project. A Solution folder isn't a real folder that has a corresponding filesystem folder, it's just virtual. So when you "add" files it just links them to the virtual folder. So a Solution Folder is more like a view. IF you do like to have them in the same "real" folder you can A. put them in the same folder before adding them. or B. store the files inside a project and use a real folder instead; if you have any suitable project for that or just create an empty one just for mics files.

**Comment by ceciliasharp** [comment]
For the installation error, I need to have a look at it. But It's good it still works. Usually, it's some version number or similar that needs to be updated once in a while, with new versions of VS.

**Comment by heribertolugo** [comment]
> I'm sorry to say that this is the design of the feature "Solution Folders". Initially, those solution folders were designed just to support; project inside a solution. To organize them into groups when having large solutions. But the structure makes them "perfect" for files not belonging to a particular project. A Solution folder isn't a real folder that has a corresponding filesystem folder, it's just virtual. So when you "add" files it just links them to the virtual folder. So a Solution Folder is more like a view. IF you do like to have them in the same "real" folder you can A. put them in the same folder before adding them. or B. store the files inside a project and use a real folder instead; if you have any suitable project for that or just create an empty one just for mics files.

thanks for getting back to me.. seems its a UI bug. I was able to check everything in even though it didnt show the icon.



> For the installation error, I need to have a look at it. But It's good it still works. Usually, it's some version number or similar that needs to be updated once in a while, with new versions of VS.

ahhh ok.. well it seems to be working correctly, even with that install error .

thanks for creating and sharing your project.
