### ISSUE TITLE
Extenstion isn't installable on VS2019

### ISSUE THREAD

**Issue by rorourke-iot** [ceciliasharp/Extension.FolderToSolutionFolder#2]
While attempting to install the extension in a fresh install of VS2019, I encountered a failure indicating no supported products were installed. I've pulled the source hoping I could find something that stands out to prevent installation, but I didn't see anything (likely because I don't grasp the specifics of extension development). The log *seems* to indicate this shouldn't fail.

[dd_VSIXInstaller_20190408133133_19b4.log](https://github.com/ceciliasharp/Extension.FolderToSolutionFolder/files/3055713/dd_VSIXInstaller_20190408133133_19b4.log)

**Comment by ceciliasharp** [comment]
fixed and deployed
