### ISSUE TITLE
cannot install 1.2 under VS2017

### ISSUE THREAD

**Issue by Fredo70** [ceciliasharp/Extension.FolderToSolutionFolder#5]
I can't install the new version 1.2 under Visual Studio 2017 anymore.

"The specified required version does not match the installed version." (translated from German)

    25.10.2019 06:46:20 - Für die Erweiterung wird ein Upgrade von Version 1.1 durchgeführt.
    25.10.2019 06:46:21 - Die Erweiterung kann für die folgenden Produkte aufgrund fehlender erforderlicher Komponenten nicht installiert werden:
    25.10.2019 06:46:21 - 	Microsoft Visual Studio Professional 2017
    25.10.2019 06:46:21 - 		-------------------------------------------------------
    25.10.2019 06:46:21 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
    25.10.2019 06:46:21 - 		Name         : Visual Studio core editor
    25.10.2019 06:46:21 - 		Version      : [16.1.28811.260,17.0)
    25.10.2019 06:46:21 - 		Error        : Die angegebene erforderliche Version entspricht nicht der installierten Version.

**Comment by ceciliasharp** [comment]
Fixed in version 1.3
