### ISSUE TITLE
Exclude .git repo folder

### ISSUE THREAD

**Issue by ryancheung** [ceciliasharp/Extension.FolderToSolutionFolder#7]
The `.git` folder is too big, it should be excluded.

**Comment by MikeRosoft** [comment]
And for the record the folder .hg (if you are using Mercurial). A case could be made to ignore folders starting with . character by default. But on the other hand, the repository directory is normally in (or below) the root of the solution. And why would you want to include the root of the solution as a subfolder of the solution itself?
